/**
 * Shanten — distance (in tile swaps) from a winning hand.
 *
 * Implements the lookup-table-friendly approach described in
 *   https://blog.ezyang.com/2014/04/calculating-shanten-in-mahjong/
 *
 * The article's key observation: the shanten contribution of one
 * suit's nine numbered tiles depends only on its 9-vector of counts
 * (each in 0..4). There are 5^9 = 1,953,125 such vectors — small
 * enough to memoize. Ditto for honors (a 7-vector, no sequences).
 *
 * For each per-suit configuration we record, for every target
 * (`m` complete melds, `p` pair flag), the maximum number of
 * `(complete_melds, partial_melds_without_pair, has_pair)` that
 * configuration can supply. The final shanten of the full hand is
 * computed by trying every distribution of the four meld budget
 * across the four components (3 suits + honors) and the pair across
 * the same four components — 140 combinations by stars-and-bars.
 *
 * In addition to the standard 4-melds-and-a-pair shape we also
 * compute chiitoitsu (7 pairs) and kokushi (13 orphans) directly,
 * since they don't fit the meld decomposition. Final shanten is the
 * minimum across all three.
 *
 * Performance: per-suit decomposition is recursive but pruned
 * aggressively (4-meld and 1-pair budget caps). Results are cached
 * in a module-level `Map` keyed by the base-5 encoding of the
 * counts vector. The first time a configuration is seen it is
 * computed; thereafter it is a constant-time lookup. This gives the
 * same asymptotic behavior as a precomputed table without the
 * 20MB memory cost or multi-second startup; for an eager
 * full-table fill see `precomputeSuitTable()`.
 *
 * Intentionally not exported from `app/game/rules/index.ts` yet —
 * Phase 1 step 3 wires this into the rules barrel after tests pass.
 */

import type { Tile } from "./types";

// ---------------------------------------------------------------------------
// Counts representation
// ---------------------------------------------------------------------------

/**
 * Per-tile-type counts for a hand: 9 manzu, 9 pinzu, 9 souzu, 7 honors.
 * Index layout matches `tileToIndex` below. Each count is in 0..4.
 */
export interface HandCounts {
  m: number[]; // length 9, indices 0..8 = 1m..9m
  p: number[];
  s: number[];
  z: number[]; // length 7, indices 0..6 = 1z..7z
}

export function emptyCounts(): HandCounts {
  return {
    m: new Array(9).fill(0),
    p: new Array(9).fill(0),
    s: new Array(9).fill(0),
    z: new Array(7).fill(0),
  };
}

export function tileToIndex(tile: Tile): {
  suit: "m" | "p" | "s" | "z";
  index: number;
} {
  const suit = tile[tile.length - 1] as "m" | "p" | "s" | "z";
  const n = tile[0] === "0" ? 5 : Number(tile[0]); // red five → 5
  return { suit, index: n - 1 };
}

export function countsFromTiles(tiles: readonly Tile[]): HandCounts {
  const c = emptyCounts();
  for (const t of tiles) {
    const { suit, index } = tileToIndex(t);
    c[suit][index]++;
  }
  return c;
}

// ---------------------------------------------------------------------------
// Per-suit decomposition (the "lookup table" body)
// ---------------------------------------------------------------------------

/**
 * Best per-suit decomposition under the 4-meld / 1-pair budget.
 *
 * - `melds`    : number of full melds (triplets or sequences) consumed.
 * - `partials` : number of partial melds (pairs-as-partial / kanchans /
 *                penchans) not counting the dedicated pair.
 *                A pair is "promoted" to the dedicated pair slot when
 *                it gives a strictly better total; otherwise it can
 *                count as a partial.
 * - `pair`     : 0 or 1 — whether a pair is reserved as the head.
 *
 * The combiner cares about three numbers per suit:
 *   - the best `(melds, partials)` *without* using a pair,
 *   - the best `(melds, partials)` *with* the pair reserved here.
 * `partials` is capped at `4 - melds` (extras give nothing).
 */
export interface SuitBlock {
  melds: number;
  partials: number;
  pair: 0 | 1;
}

interface SuitBest {
  /** Best with no pair reserved in this suit. */
  noPair: { melds: number; partials: number };
  /** Best with the pair reserved in this suit, or `null` if impossible. */
  withPair: { melds: number; partials: number } | null;
}

const SUIT_CACHE = new Map<number, SuitBest>();
const HONOR_CACHE = new Map<number, SuitBest>();

/**
 * Optional precomputed per-suit lookup table. Dense Uint8Array of
 * length 2 * 5^9, indexed by base-5 encoding of the 9-vector counts:
 *   bytes[2k+0] = noPair.melds * 5 + noPair.partials
 *   bytes[2k+1] = withPair == null ? 0xFF : melds * 5 + partials
 *
 * Generated by `scripts/_generate-shanten-table.ts` and loaded
 * lazily under Node. The loader is gated on a runtime
 * `typeof process` check and uses dynamic `await import` so the
 * client bundle never references `node:fs` / `node:url`. When the
 * table is absent (browser, or when running the generator itself
 * for the first time), `solveSuit` falls back to the lazy
 * recursive cache below.
 */
let SUIT_TABLE: Uint8Array | null = null;
if (
  typeof process !== "undefined" &&
  typeof process.versions?.node === "string"
) {
  try {
    const { readFileSync } = await import("node:fs");
    const { fileURLToPath } = await import("node:url");
    const path = fileURLToPath(
      new URL("./shanten-suit-table.bin", import.meta.url)
    );
    const buf = new Uint8Array(readFileSync(path));
    if (buf.length === 2 * 5 ** 9) {
      SUIT_TABLE = buf;
    }
  } catch {
    SUIT_TABLE = null;
  }
}

/** Test/debug accessor: true iff the precomputed table is in use. */
export function isSuitTableLoaded(): boolean {
  return SUIT_TABLE !== null;
}

/** Encode a counts vector (each 0..4) as a base-5 integer. */
function encode(counts: readonly number[]): number {
  let v = 0;
  for (let i = counts.length - 1; i >= 0; i--) {
    v = v * 5 + counts[i];
  }
  return v;
}

/**
 * Recursively decompose a numbered-suit configuration. Returns the
 * Pareto-best `(melds, partials)` achievable both with and without a
 * reserved pair in this suit, capped by the 4-meld budget.
 */
export function solveSuit(counts: readonly number[]): SuitBest {
  const key = encode(counts);
  if (SUIT_TABLE !== null) {
    const offset = key * 2;
    const np = SUIT_TABLE[offset];
    const wp = SUIT_TABLE[offset + 1];
    return {
      noPair: { melds: (np / 5) | 0, partials: np % 5 },
      withPair: wp === 0xff ? null : { melds: (wp / 5) | 0, partials: wp % 5 },
    };
  }
  const cached = SUIT_CACHE.get(key);
  if (cached) {
    return cached;
  }
  const work = [...counts];
  const result: SuitBest = {
    noPair: { melds: 0, partials: 0 },
    withPair: null,
  };
  exploreSuit(work, 0, 0, 0, false, result);
  SUIT_CACHE.set(key, result);
  return result;
}

function better(
  a: { melds: number; partials: number },
  b: { melds: number; partials: number }
): { melds: number; partials: number } {
  // Prefer more melds; break ties with more partials.
  if (b.melds > a.melds) {
    return b;
  }
  if (b.melds === a.melds && b.partials > a.partials) {
    return b;
  }
  return a;
}

function exploreSuit(
  c: number[],
  i: number,
  melds: number,
  partials: number,
  pairUsed: boolean,
  out: SuitBest
): void {
  // Skip leading zeros.
  while (i < 9 && c[i] === 0) {
    i++;
  }
  if (i === 9) {
    record(out, melds, partials, pairUsed);
    return;
  }
  // Pruning: more than 4 melds (incl partials) helps no one.
  if (melds + partials >= 4 && melds < 4) {
    // We can still finish out melds, but partials beyond this point
    // are wasted. Allow continuing for completeness.
  }

  // Option: triplet at i.
  if (c[i] >= 3 && melds < 4) {
    c[i] -= 3;
    exploreSuit(c, i, melds + 1, partials, pairUsed, out);
    c[i] += 3;
  }
  // Option: sequence i,i+1,i+2.
  if (i <= 6 && c[i] >= 1 && c[i + 1] >= 1 && c[i + 2] >= 1 && melds < 4) {
    c[i]--;
    c[i + 1]--;
    c[i + 2]--;
    exploreSuit(c, i, melds + 1, partials, pairUsed, out);
    c[i]++;
    c[i + 1]++;
    c[i + 2]++;
  }
  // Option: pair at i (reserve as the head pair).
  if (c[i] >= 2 && !pairUsed) {
    c[i] -= 2;
    exploreSuit(c, i, melds, partials, true, out);
    c[i] += 2;
  }
  // Option: pair at i counted as a partial (toitsu candidate, not head).
  if (c[i] >= 2 && melds + partials < 4) {
    c[i] -= 2;
    exploreSuit(c, i, melds, partials + 1, pairUsed, out);
    c[i] += 2;
  }
  // Option: edge/closed wait i,i+1 (penchan/ryanmen).
  if (i <= 7 && c[i] >= 1 && c[i + 1] >= 1 && melds + partials < 4) {
    c[i]--;
    c[i + 1]--;
    exploreSuit(c, i, melds, partials + 1, pairUsed, out);
    c[i]++;
    c[i + 1]++;
  }
  // Option: kanchan (closed) i,i+2.
  if (i <= 6 && c[i] >= 1 && c[i + 2] >= 1 && melds + partials < 4) {
    c[i]--;
    c[i + 2]--;
    exploreSuit(c, i, melds, partials + 1, pairUsed, out);
    c[i]++;
    c[i + 2]++;
  }
  // Option: drop one of c[i] (tile is a floater).
  c[i]--;
  exploreSuit(c, i, melds, partials, pairUsed, out);
  c[i]++;
}

function record(
  out: SuitBest,
  melds: number,
  partials: number,
  pairUsed: boolean
): void {
  // Cap partials at the remaining meld slots — extras don't help shanten.
  const cappedPartials = Math.min(partials, 4 - melds);
  const candidate = { melds, partials: cappedPartials };
  if (pairUsed) {
    out.withPair = out.withPair ? better(out.withPair, candidate) : candidate;
  } else {
    out.noPair = better(out.noPair, candidate);
  }
}

/**
 * Honors decomposition: only triplets and pairs are valid (no sequences).
 */
export function solveHonors(counts: readonly number[]): SuitBest {
  const key = encode(counts);
  const cached = HONOR_CACHE.get(key);
  if (cached) {
    return cached;
  }
  let melds = 0;
  let partials = 0;
  let pairs = 0;
  for (const n of counts) {
    if (n >= 3) {
      melds++;
    } else if (n === 2) {
      pairs++;
    }
  }
  // The pair slot can be at most one of the pairs; the rest become
  // partials.
  const noPairPartials = Math.min(pairs, 4 - melds);
  const result: SuitBest = {
    noPair: { melds, partials: noPairPartials },
    withPair:
      pairs >= 1 ? { melds, partials: Math.min(pairs - 1, 4 - melds) } : null,
  };
  partials = pairs;
  void partials;
  HONOR_CACHE.set(key, result);
  return result;
}

// ---------------------------------------------------------------------------
// Standard shanten (4 melds + 1 pair)
// ---------------------------------------------------------------------------

/**
 * Standard-form shanten. Per the ezyang derivation:
 *   shanten = 8 - 2 * melds - max(partials + pair, ...)
 *   with constraints: melds + partials ≤ 4, pair ≤ 1.
 *
 * Iterates the four (3 suits + honors) Pareto-best blocks:
 *   - try the pair coming from each suit (or no pair),
 *   - sum melds + partials,
 *   - apply the standard formula.
 */
export function standardShanten(counts: HandCounts): number {
  const blocks = [
    solveSuit(counts.m),
    solveSuit(counts.p),
    solveSuit(counts.s),
    solveHonors(counts.z),
  ];

  let best = 8;

  // No pair anywhere.
  const noPair = blocks.map((b) => b.noPair);
  best = Math.min(best, scoreCombo(noPair, false));

  // Pair from suit i.
  for (let i = 0; i < 4; i++) {
    if (!blocks[i].withPair) {
      continue;
    }
    const combo = blocks.map((b, j) =>
      j === i ? blocks[i].withPair! : b.noPair
    );
    best = Math.min(best, scoreCombo(combo, true));
  }
  return best;
}

function scoreCombo(
  blocks: { melds: number; partials: number }[],
  hasPair: boolean
): number {
  let melds = 0;
  let partials = 0;
  for (const b of blocks) {
    melds += b.melds;
    partials += b.partials;
  }
  // Cap melds + partials at 4 (Pareto already enforces per-block, but
  // crossings can push the total over).
  if (melds + partials > 4) {
    partials = 4 - melds;
  }
  return 8 - 2 * melds - partials - (hasPair ? 1 : 0);
}

// ---------------------------------------------------------------------------
// Special hands
// ---------------------------------------------------------------------------

/** Chiitoitsu: 7 distinct pairs. */
export function chiitoitsuShanten(counts: HandCounts): number {
  let pairs = 0;
  let kinds = 0;
  for (const arr of [counts.m, counts.p, counts.s, counts.z]) {
    for (const n of arr) {
      if (n >= 1) {
        kinds++;
      }
      if (n >= 2) {
        pairs++;
      }
    }
  }
  // 6 - pairs is the meld-shanten; bump by the deficit of distinct
  // tile kinds (you cannot have more pairs than kinds, and chiitoitsu
  // forbids identical pairs).
  let shanten = 6 - pairs;
  if (kinds < 7) {
    shanten += 7 - kinds;
  }
  return shanten;
}

/** Kokushi musou: 13 orphans (terminals + honors), one paired. */
export function kokushiShanten(counts: HandCounts): number {
  const orphans: number[] = [];
  orphans.push(counts.m[0], counts.m[8]);
  orphans.push(counts.p[0], counts.p[8]);
  orphans.push(counts.s[0], counts.s[8]);
  for (const n of counts.z) {
    orphans.push(n);
  }
  let kinds = 0;
  let hasPair = 0;
  for (const n of orphans) {
    if (n >= 1) {
      kinds++;
    }
    if (n >= 2) {
      hasPair = 1;
    }
  }
  return 13 - kinds - hasPair;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Shanten of a closed hand: minimum number of tile swaps (replacing
 * one tile with another) needed to reach tenpai (-1 means winning).
 *
 * Accepts either a tile-string array (any length 1..14) or an
 * already-built `HandCounts`. The function does not enforce a
 * particular tile count; callers can compute "what would my shanten
 * be if I drew this tile?" by appending and re-querying.
 */
export function shanten(input: readonly Tile[] | HandCounts): number {
  const counts = Array.isArray(input)
    ? countsFromTiles(input as readonly Tile[])
    : (input as HandCounts);
  return Math.min(
    standardShanten(counts),
    chiitoitsuShanten(counts),
    kokushiShanten(counts)
  );
}

/**
 * Tiles whose addition would strictly reduce shanten — i.e. the
 * "ukeire" / acceptance set for the hand. Includes red-five-aware
 * iteration: only the canonical 5 is tested per suit.
 */
export function acceptanceTiles(input: readonly Tile[] | HandCounts): Tile[] {
  const counts = Array.isArray(input)
    ? countsFromTiles(input as readonly Tile[])
    : ({
        m: [...(input as HandCounts).m],
        p: [...(input as HandCounts).p],
        s: [...(input as HandCounts).s],
        z: [...(input as HandCounts).z],
      } as HandCounts);
  const baseline = shanten(counts);
  const out: Tile[] = [];
  const suits: Array<"m" | "p" | "s"> = ["m", "p", "s"];
  for (const suit of suits) {
    for (let i = 0; i < 9; i++) {
      if (counts[suit][i] >= 4) {
        continue;
      }
      counts[suit][i]++;
      if (shanten(counts) < baseline) {
        out.push(`${i + 1}${suit}`);
      }
      counts[suit][i]--;
    }
  }
  for (let i = 0; i < 7; i++) {
    if (counts.z[i] >= 4) {
      continue;
    }
    counts.z[i]++;
    if (shanten(counts) < baseline) {
      out.push(`${i + 1}z`);
    }
    counts.z[i]--;
  }
  return out;
}

/** True iff the hand is tenpai (shanten === 0 with 13-tile hand). */
export function isTenpai(input: readonly Tile[] | HandCounts): boolean {
  return shanten(input) === 0;
}

/**
 * Wait tiles for a tenpai hand: the subset of acceptance tiles
 * that still has at least one unseen copy in the seat's own hand
 * — i.e. tiles where the seat does not already hold all four
 * copies (kara-ten wait).
 *
 * Returns `[]` for non-tenpai hands and for "no-wait tenpai"
 * shapes such as `123m123p234s9999s` where `shanten()` reports 0
 * but every wait copy is locked in the hand itself. A non-empty
 * result is the canonical "is tenpai for riichi / tenpai-payment
 * purposes" predicate.
 */
export function waits(input: readonly Tile[] | HandCounts): Tile[] {
  const counts = Array.isArray(input)
    ? countsFromTiles(input as readonly Tile[])
    : (input as HandCounts);
  if (shanten(counts) !== 0) {
    return [];
  }
  return acceptanceTiles(counts);
}

// ---------------------------------------------------------------------------
// Optional eager precompute
// ---------------------------------------------------------------------------

/**
 * Eagerly fill the per-suit cache for every reachable counts vector
 * up to a given total tile count. Useful when the caller wants the
 * lookup behavior at startup instead of warming on demand.
 *
 * Cost: ~5^9 / 2 reachable entries, ≤2 seconds on a modern laptop.
 */
export function precomputeSuitTable(maxTotal = 14): void {
  const c = new Array(9).fill(0);
  fill(c, 0, 0, maxTotal);
}

function fill(c: number[], i: number, sum: number, maxTotal: number): void {
  if (i === 9) {
    solveSuit(c);
    return;
  }
  for (let n = 0; n <= 4 && sum + n <= maxTotal; n++) {
    c[i] = n;
    fill(c, i + 1, sum + n, maxTotal);
  }
  c[i] = 0;
}

/**
 * Fast "is this a winning shape?" check for ron / tsumo gating.
 *
 * Returns `true` iff the concealed hand + already-declared melds +
 * the candidate `winTile` form a valid agari shape (standard 4
 * melds + 1 pair, chiitoitsu, or kokushi). This is a shape-only
 * check — yaku, dora, fu, riichi, etc. are not considered. Callers
 * still need to call `scoreHand` for the yaku gate, but can short-
 * circuit the expensive call when this returns `false`.
 *
 * Kans are normalized to triplets for shape purposes (one tile per
 * kan dropped from the counts) so the underlying algorithms see a
 * standard 14-tile picture.
 */
export function isWinningShape(
  hand: readonly Tile[],
  melds: readonly { tiles: readonly Tile[] }[],
  winTile: Tile
): boolean {
  const counts = countsFromTiles(hand);
  for (const m of melds) {
    // Add the meld tiles back, but cap kan contributions at 3 so
    // shape totals stay in the 14-tile budget.
    const limit = m.tiles.length === 4 ? 3 : m.tiles.length;
    for (let i = 0; i < limit; i++) {
      const { suit, index } = tileToIndex(m.tiles[i]);
      counts[suit][index]++;
    }
  }
  const wt = tileToIndex(winTile);
  counts[wt.suit][wt.index]++;
  if (standardShanten(counts) === -1) {
    return true;
  }
  // Chiitoitsu / kokushi require a fully concealed hand.
  if (melds.length === 0) {
    if (chiitoitsuShanten(counts) === -1) {
      return true;
    }
    if (kokushiShanten(counts) === -1) {
      return true;
    }
  }
  return false;
}
